import React from 'react';

const TermsOfService = () => {
    return (
        <div
            style={{
                padding: "20px",
                maxWidth: "800px",
                margin: "auto",
                fontFamily: "Arial, sans-serif",
                lineHeight: "1.6",
                color: "#333",
                backgroundColor: "#f9f9f9",
                borderRadius: "8px",
                boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
            }}
        >
            <div style={{ fontFamily: "Arial, sans-serif", margin: "20px", lineHeight: "1.6" }}>
                <h1 style={{ textAlign: "center" }}>Terms of Service</h1>
                <p>As you sign-up for a Bravit Pharmaceuticals Private Limited Account or by using any Bravit's Services, you are agreeing to be bound by the following terms and conditions:</p>
                <p>As used in these Terms of Service, “we”, “us” and “Bravit” means the applicable Bravit Contracting Party.</p>
                <p>The services offered by Bravit Pharmaceuticals Private Limited under the Terms of Service include various products and online services by enabling you for online purchase in person. Any such services offered by Bravit Pharmaceuticals Private Limited are referred to in these Terms of Services. Any new features or tools which are added to the current Services shall be also subject to the Terms of Service. You can review the current version of the Terms of Service at any time at <a href="https://www.bravitpharmaceuticals.com">https://www.bravitpharmaceuticals.com</a>. Bravit Pharmaceuticals Private Limited reserves the right to update and change the Terms of Service by posting updates and changes to the Bravit Pharmaceuticals Private Limited website. You are advised to check the Terms of Service from time to time for any updates or changes that may impact you. and if you do not accept such amendments, you must cease using the services.</p>
                <p>You must read and agree with and accept all of the terms and conditions contained or expressly referenced in these Terms of Service, including Bravit Pharmaceuticals Private Limited’s Acceptable Use Policy and Privacy Policy. The Bravit Pharmaceuticals Private Limited API License and Terms of Use and the Bravit Pharmaceuticals Private Limited Data Processing Addendum before you may sign up for a Bravit Pharmaceuticals Private Limited Account or use any Bravit Pharmaceuticals Private Limited Service.</p>
                <p>Everyday language summaries are provided for convenience only and appear in bold under each section, but these summaries are not legally binding. Please read the Terms of Service, including any document referred to in these Terms of Service, for the complete picture of your legal requirements. By using Bravit Pharmaceuticals Private Limited or any Bravit Pharmaceuticals Private Limited services, you are agreeing to these terms and be sure to occasionally check back for updates.</p>
                <h2>1. Account Terms</h2>
                <p>You must be 18 years or older or at least the age of majority in the jurisdiction where you reside or from which you use this Service. To access and use the Services, you must register for a Bravit Pharmaceuticals Private Limited account (“Account”) by providing your full legal name, current address, phone number, a valid email address, and any other information indicated as required. Bravit Pharmaceuticals Private Limited may reject your application for an Account, or cancel an existing Account, for any reason, in our sole discretion. You acknowledge that Bravit Pharmaceuticals Private Limited will use the email address you provide as the primary method for communication. You are responsible for keeping your password secure. Bravit Pharmaceuticals Private Limited cannot and will not be liable for any loss or damage from your failure to maintain the security of your Account and password. You are responsible for all activity and content such as photos, images, videos, graphics, written content, audio files, code, information, or data uploaded, collected, generated, stored, displayed, distributed, transmitted or exhibited on or in connection with your Account (“Materials”). A breach or violation of any term in the Terms of Service, including the AUP, as determined in the sole discretion of Bravit Pharmaceuticals Private Limited will result in an immediate termination of your services.</p>
                <h2>2. Account Activation</h2>
                <p>Subject to section 2.1, the person signing up for the Service will be the contracting party (“Account Owner”) for the purposes of our Terms of Service and will be the person who is authorized to use any corresponding account we may provide to the Account Owner in connection with the Service. If you are signing up for the Service on behalf of your employer, your employer shall be the Account Owner. If you are signing up for the Service on behalf of your employer, then you represent and warrant that you have the authority to bind your employer to our Terms of Service. Accounts registered by “bots” or other automated methods are not permitted.</p>
                <h2>3. General Conditions</h2>
                <p>You must read, agree with and accept all of the terms and conditions contained in these Terms of Service, including the AUP and the Privacy Policy before you may become a Bravit Pharmaceuticals Private Limited user. Technical support is only provided to paying Account holders and is only available via email. The Terms of Service shall be governed by and interpreted in accordance with the laws of the State of Maharashtra and the laws of India applicable therein, without regard to principles of conflicts of laws. The parties irrevocably and unconditionally submit to the exclusive jurisdiction of the courts of the State of Maharashtra with respect to any dispute or claim arising out of or in connection with the Terms of Service. You acknowledge and agree that Bravit Pharmaceuticals Private Limited may amend these Terms of Service at any time by posting the relevant amended and restated Terms of Service on the Bravit Pharmaceuticals Private Limited website, available at <a href="https://www.bravitpharmaceuticals.com">https://www.bravitpharmaceuticals.com</a> and such amendments to the Terms of Service are effective as of the date of posting. Your continued use of the Services after the amended Terms of Service are posted to the Bravit Pharmaceuticals Private Limited website constitutes your agreement to, and acceptance of, the amended Terms of Service. If you do not agree to any changes to the Terms of Service, do not continue to use the Service. You may not use the Bravit Pharmaceuticals Private Limited service for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws) as well as the laws of India. You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service without the express written permission by Bravit Pharmaceuticals Private Limited. You shall not purchase search engine or other pay per click keywords (such as Google AdWords), or domain names that use Bravit Pharmaceuticals Private Limited or Bravit Pharmaceuticals Private Limited trademarks and/or variations and misspellings thereof.</p>
                <h2>4. Bravit Pharmaceuticals Private Limited Rights</h2>
                <p>We reserve the right to modify or terminate the Service for any reason, without notice at any time. We reserve the right to refuse service to anyone for any reason at any time. We may, but have no obligation to, remove Materials and suspend or terminate Accounts if we determine in our sole discretion that the goods or services offered via a store, or the Materials uploaded or posted to a store, violate our Acceptable Use Policy (“AUP”) or these Terms of Service. Verbal or written abuse of any kind (including threats of abuse or retribution) of any Bravit Pharmaceuticals Private Limited customer, Bravit Pharmaceuticals Private Limited employee, member, or officer will result in immediate Account termination. Bravit Pharmaceuticals Private Limited does not pre-screen Materials and it is in our sole discretion to refuse or remove any Materials from the Service.</p>
                <h2>5. Limitation of Liability</h2>
                <p>You expressly understand and agree that Bravit Pharmaceuticals Private Limited shall not be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses resulting from the use of or inability to use the service. In no event shall Bravit Pharmaceuticals Private Limited or our suppliers be liable for lost profits or any special, incidental or consequential damages arising out of or in connection with our site, our services or these Terms of Service (however arising including negligence). You agree to indemnify and hold us and (as applicable) our parent, subsidiaries, affiliates, Bravit Pharmaceuticals Private Limited partners, officers, directors, agents, employees, and suppliers harmless from any claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of your breach of these Terms of Service or the documents it incorporates by reference or your violation of any law or the rights of a third party. Your use of the Service is at your sole risk. The Service is provided on an “as is” and “as available” basis without any warranty or condition, express, implied or statutory. Bravit Pharmaceuticals Private Limited does not warrant that the Service will be uninterrupted, timely, secure, or error-free. Bravit Pharmaceuticals Private Limited does not warrant that the results that may be obtained from the use of the Service will be accurate or reliable. Bravit Pharmaceuticals Private Limited does not warrant that the quality of any products, services, information, or other Materials purchased or obtained by you through the Service will meet your expectations, or that any errors in the Service will be corrected.</p>
                <h2>6. Waiver and Complete Agreement</h2>
                <p>The failure of Bravit Pharmaceuticals Private Limited to exercise or enforce any right or provision of the Terms of Service shall not constitute a waiver of such right or provision. The Terms of Service constitutes the entire agreement between you and Bravit Pharmaceuticals Private Limited and govern your use of the Service, superseding any prior agreements between you and Bravit Pharmaceuticals Private Limited (including, but not limited to, any prior versions of the Terms of Service).</p>
                <h2>7. Intellectual Property and Customer Content</h2>
                <p>We do not claim any intellectual property rights over the Materials you provide to the Bravit Pharmaceuticals Private Limited service. All Materials you upload remains yours. You can remove your Bravit Pharmaceuticals Private Limited store at any time by deleting your Account. By uploading Materials, you agree: (a) to allow other internet users to view the Materials you post publicly to your store; (b) to allow Bravit Pharmaceuticals Private Limited to store, and in the case of Materials you post publicly, display and use your Materials; (c) that Bravit Pharmaceuticals Private Limited can, at any time, review and delete any Materials posted in your store or on the Service, in accordance with this Agreement.</p>
                <p>Effective Date: [Insert date]</p>
            </div>
        </div>
    );
};

export default TermsOfService;
